### ISSUE TITLE
Restart addon or Host SSL Error 

### ISSUE THREAD

**Issue by madwurst666** [Flodu31/HomeAssistant-PeugeotIntegration#13]
Hi
The Addon and the Dashboard run after Installation . Sensors was not working in my coniguration. After i reboot the Host or addon  i get these error in my log. My hass can‘t restart the addon i must reinstall and reconfig the addon.

Containerised psa_car_controller loading...
/usr/local/lib/python3.7/dist-packages/dash_bootstrap_components/_table.py:5: UserWarning: 
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html
2021-10-04 13:56:04,346 :: INFO :: save config change
2021-10-04 13:56:05,585 :: INFO :: ["{'vin': 'VXKUKZKXZxxxxxxx', 'vehicle_id': 'xxxxxxxxxxxxxxxxxxxxxx16861545663774d44597a4e44676a49324d334f44417a4d575935595449774f54646a4e5456694d6a526c5a6a59334d3251774d44526b4f4749344d6a5979596a56694e6a526b59544d324d54466a4d4451795a4759315a574a6a59544  Xxxxxxxxxxxxxxxxxx', 'label': 'Mokka-e', 'brand': 'C', 'abrp_name': 'opel:corsae:20:50', 'battery_power': 46, 'fuel_capacity': 0, 'max_elec_consumption': 70, 'max_fuel_consumption': 0}"]
2021-10-04 13:56:06,039 :: INFO :: save config change
Traceback (most recent call last):
  File "/psa_car_controller/server.py", line 15, in <module>
    conf.load_app()
  File "/psa_car_controller/libs/config.py", line 103, in load_app
    self.start_remote_control()
  File "/psa_car_controller/libs/config.py", line 63, in start_remote_control
    self.myp.start_mqtt()
  File "/psa_car_controller/my_psacc.py", line 341, in start_mqtt
    self.mqtt_client.connect(MQTT_SERVER, 8885, 60)
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 1104, in reconnect
    sock.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)

**Comment by Flodu31** [comment]
Hi,

https://github.com/flobz/psa_car_controller/issues/234

Issue from Peugeot apparently.
Florent

**Comment by madwurst666** [comment]
Hi
Thx for the fast Information.
Danny
