### ISSUE TITLE
After adding DuckDsn, psa control no longer works, gives certificate error in add-on

### ISSUE THREAD

**Issue by wingmanx** [Flodu31/HomeAssistant-PeugeotIntegration#58]
After adding DuckDsn, psa control no longer works, gives certificate error in add-on.
I can see the Summary, Trips, Charge, but the "Control" where is the battery state and other sensors no longer works.
Everything worked before, and also a few days after having DuckDns.
To check for connection, used to place the address in address bar like this:
https://192.168.0.10:5000/get_vehicleinfo/<VIN>

Now it says in the browser:

Secure Connection Failed

An error occurred during a connection to 192.168.0.10:5000. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.

**Comment by iendicott** [comment]
Have you tried http://192.168.0.10:5000/get_vehicleinfo/
You won't be able to use https with an IP unless your certificate is also named 192.168.0.10

HTH

**Comment by boab21mac** [comment]
Seems the entire integration has gone down?  From RobertSent from my iPhone On 24 Nov 2023, at 15:09, Ivan Endicott ***@***.***> wrote:﻿
Have you tried http://192.168.0.10:5000/get_vehicleinfo/
You won't be able to use https with an IP unless your certificate is also named 192.168.0.10
HTH

**Comment by iendicott** [comment]
![Capture](https://github.com/Flodu31/HomeAssistant-PeugeotIntegration/assets/73525618/fd9ca79f-ac68-4f8f-8425-7d7200fde50e)
Yes just looked on my dashboard seems mine has gone as well.

**Comment by boab21mac** [comment]
From RobertSent from my iPhone On 24 Nov 2023, at 15:23, Ivan Endicott ***@***.***> wrote:﻿
Yes just looked on my dashboard seems mine has gone as well.

**Comment by BrunoNogu** [comment]
Yup. Mine too :(

**Comment by wingmanx** [comment]
http://192.168.0.10:5000/get_vehicleinfo/
shows the car summary without any values.

http://192.168.0.10:5000/get_vehicleinfo/<VIN> gives:
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

With DuckDns I can no longer access http in the home network, only through https.

**Comment by wingmanx** [comment]
Well, just updated PSA Car Controller from version 3.1.0 to the new 3.2.0 and it working again!!!

**Comment by iendicott** [comment]
I too can confirm 3.2.0 fixes the issue. Massive thanks to the developer for fixing this.

**Comment by boab21mac** [comment]
Agreed working!!Great job!!From RobertSent from my iPhone On 26 Nov 2023, at 16:05, Ivan Endicott ***@***.***> wrote:﻿
I too can confirm 3.2.0 fixes the issue. Massive thanks to the developer for fixing this.

**Comment by wingmanx** [comment]
Hi guys.
Is your PSA add-on still working? Since yesterday, I've lost access to the PSA info in the add on.
When I try to configure again it says:Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 50, in firstLaunchConfig token = res.json()["accessToken"] KeyError: 'accessToken' HOST_BRANDID : https://id-dcr.peugeot.com/mobile-services sitecode: AP_PT_ESP{"session":"332325c85601d6b849db5353b03b4c0d","returnCode":"NEED_AUTHORIZATION"," ..................

**Comment by iendicott** [comment]
Yes working for me.
I am guessing it might be worth re-running through the user config within the "PSA Car Controller" plugin based on the last part of the message "NEED_AUTHORIZATION" ?

**Comment by wingmanx** [comment]
This message I've shared, appears when I run the add-on, user config, insert the login data and click "submit" ...
So, this time instead of selecting PT, I've selected GB and it worked!
So, all working again.

**Comment by wingmanx** [comment]
Hi guys ... Yesterday I've lost access to PSA in HA.
I've tried again to login with GB option, but now it says:
"400 - server_error : Internal Server Error"

All the other options don't work, FR, PT, PL, and a few more ... They all give this error:
Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 50, in firstLaunchConfig token = res.json()["accessToken"] KeyError: 'accessToken' HOST_BRANDID : https://id-dcr.peugeot.com/mobile-services sitecode: AP_PT_ESP{"session":"6c2808580c93d727871bb4a84fee4e0e","returnCode":"NEED_AUTHORIZATION","token":"92757xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","fields":{"USR_PASSWORD":"SETPWD_LABEL_8"}}

I believe this happened after the last HA Core update to 2024.2.2

**Comment by wingmanx** [comment]
Guys, are you PSA Add-on working?
My says this in the log:

File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1229, in get_vehicle_status
    (data) = self.get_vehicle_status_with_http_info(id, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1293, in get_vehicle_status_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 109, in call_api
    return self._ApiClient__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 147, in __call_api
    self.update_params_for_auth(header_params, query_params, auth_settings)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 504, in update_params_for_auth
    auth_setting = self.configuration.auth_settings().get(auth)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/configuration.py", line 241, in auth_settings
    'value': 'Bearer ' + self.access_token
TypeError: can only concatenate str (not "NoneType") to str

**Comment by boab21mac** [comment]
Nope still not working, some people have had luck doing a work around but way over my head!From RobertSent from my iPhone On 24 Feb 2024, at 18:59, wingmanx ***@***.***> wrote:﻿
Guys, are you PSA Add-on working?
My says this in the log:
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1229, in get_vehicle_status
(data) = self.get_vehicle_status_with_http_info(id, **kwargs)  # noqa: E501
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api/vehicles_api.py", line 1293, in get_vehicle_status_with_http_info
return self.api_client.call_api(
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 109, in call_api
return self._ApiClient__call_api(resource_path, method,
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 147, in __call_api
self.update_params_for_auth(header_params, query_params, auth_settings)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 504, in update_params_for_auth
auth_setting = self.configuration.auth_settings().get(auth)
File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/configuration.py", line 241, in auth_settings
'value': 'Bearer ' + self.access_token
TypeError: can only concatenate str (not "NoneType") to str

**Comment by dreimer1986** [comment]
Even when I risk to say the same thing again and again... This is nothing @Flodu31 can help you. If you want to report these problems to the right person, go to flobz' repo. But on this case I hope this one will fix our problems. https://github.com/flobz/psa_car_controller/pull/772

**Comment by wingmanx** [comment]
Thanks, working now.
