### ISSUE TITLE
Server error after update home assistant to 2024.1.3

### ISSUE THREAD

**Issue by benze72** [Flodu31/HomeAssistant-PeugeotIntegration#64]
Hello, after updating Home Assistant von 2023.12.4 to 2024.1.3, the PSA Car Controller no longer works.
Even after restoring to 2023.12.4 the PSA Car Controller does not work with the same error.

Log:

`2024-01-13 19:16:51,580 :: INFO :: App version 3.3.1 2024-01-13 19:16:51,581 :: ERROR :: No config file 2024-01-13 19:16:51,583 :: WARNING :: Can't get language 2024-01-13 19:16:51,583 :: WARNING :: Can't get language 2024-01-13 19:16:52,355 :: INFO :: update_data 2024-01-13 19:16:52,583 :: INFO :: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit) 2024-01-13 19:17:44,863 :: INFO :: App version 3.3.1 2024-01-13 19:17:44,864 :: ERROR :: No config file 2024-01-13 19:17:44,867 :: WARNING :: Can't get language 2024-01-13 19:17:44,867 :: WARNING :: Can't get language 2024-01-13 19:17:45,689 :: INFO :: update_data 2024-01-13 19:17:45,716 :: INFO :: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit) 2024-01-13 19:18:14,028 :: INFO :: 172.30.32.1 - - [13/Jan/2024 19:18:14] "[37mGET / HTTP/1.1[0m" 200 - 2024-01-13 19:18:14,040 :: INFO :: 172.30.32.1 - - [13/Jan/2024 19:18:14] "[37mGET /assets/99_custom_overides.css HTTP/1.1[0m" 200 - 2024-01-13 19:18:14,047 :: INFO :: 172.30.32.1 - - [13/Jan/2024 19:18:14] "[37mGET /assets/clientside.js HTTP/1.1[0m" 200 - 2024-01-13 19:18:14,174 :: INFO :: 172.30.32.1 - - [13/Jan/2024 19:18:14] "[37mGET /_dash-layout HTTP/1.1[0m" 200 - 2024-01-13 19:18:14,176 :: INFO :: 172.30.32.1 - - [13/Jan/2024 19:18:14] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 - 2024-01-13 19:18:14,212 :: INFO :: 172.30.32.1 - - [13/Jan/2024 19:18:14] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 - 2024-01-13 19:18:14,242 :: INFO :: 172.30.32.1 - - [13/Jan/2024 19:18:14] "[37mGET /assets/images/settings.svg HTTP/1.1[0m" 200 - 2024-01-13 19:18:14,251 :: INFO :: 172.30.32.1 - - [13/Jan/2024 19:18:14] "[37mGET /config_login HTTP/1.1[0m" 200 - 2024-01-13 19:18:14,295 :: INFO :: 172.30.32.1 - - [13/Jan/2024 19:18:14] "[37mGET /_dash-layout HTTP/1.1[0m" 200 - 2024-01-13 19:18:14,297 :: INFO :: 172.30.32.1 - - [13/Jan/2024 19:18:14] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 - 2024-01-13 19:18:14,355 :: INFO :: 172.30.32.1 - - [13/Jan/2024 19:18:14] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 - 2024-01-13 19:18:14,402 :: INFO :: 172.30.32.1 - - [13/Jan/2024 19:18:14] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 - 2024-01-13 19:18:14,405 :: INFO :: 172.30.32.1 - - [13/Jan/2024 19:18:14] "[37mPOST /_dash-update-component HTTP/1.1[0m" 204 - 2024-01-13 19:18:14,407 :: INFO :: 172.30.32.1 - - [13/Jan/2024 19:18:14] "[37mPOST /_dash-update-component HTTP/1.1[0m" 204 - 2024-01-13 19:19:01,652 :: INFO :: Starting analysis on AndroidManifest.xml 2024-01-13 19:19:01,669 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:01,669 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:01,671 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:01,672 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:01,674 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:01,679 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:01,680 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:01,680 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:01,681 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:01,685 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:01,733 :: INFO :: APK file was successfully validated! 2024-01-13 19:19:01,734 :: WARNING :: Requested API level 33 is larger than maximum we have, returning API level 28 instead. 2024-01-13 19:19:04,139 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:04,140 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:04,142 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:04,145 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:04,147 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:04,151 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:04,152 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:04,154 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:04,155 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:04,156 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:04,160 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:09,660 :: ERROR :: 400 - server_error : Internal Server Error Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/web/view/config_views.py", line 133, in connectPSA res = firstLaunchConfig(app_name, email, password, countrycode) File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 95, in firstLaunchConfig psacc.connect(client_email, client_password) File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psacc/application/psa_client.py", line 35, in connect self.manager.init_with_user_credentials_realm(user, password, self.realm) File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/oauth.py", line 26, in init_with_user_credentials_realm self._token_request(self._grant_password_request_realm(login, password, realm), True) File "/usr/local/lib/python3.9/dist-packages/oauth2_client/credentials_manager.py", line 205, in _token_request CredentialManager._handle_bad_response(response) File "/usr/local/lib/python3.9/dist-packages/oauth2_client/credentials_manager.py", line 87, in _handle_bad_response raise OAuthError(HTTPStatus(response.status_code), error.get('error'), error.get('error_description')) oauth2_client.credentials_manager.OAuthError: 400 - server_error : Internal Server Error 2024-01-13 19:19:09,667 :: INFO :: 172.30.32.1 - - [13/Jan/2024 19:19:09] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 - 2024-01-13 19:19:13,343 :: INFO :: Starting analysis on AndroidManifest.xml 2024-01-13 19:19:13,344 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:13,344 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:13,346 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:13,347 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:13,348 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:13,351 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:13,352 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:13,352 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:13,352 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:13,355 :: INFO :: Namespace mapping (55, 449) already seen! This is usually not a problem but could indicate packers or broken AXML compilers. 2024-01-13 19:19:13,392 :: INFO :: APK file was successfully validated! 2024-01-13 19:19:13,393 :: WARNING :: Requested API level 33 is larger than maximum we have, returning API level 28 instead. 2024-01-13 19:19:15,733 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:15,734 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:15,736 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:15,739 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:15,742 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:15,745 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:15,746 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:15,747 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:15,748 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:15,750 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:15,752 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported 2024-01-13 19:19:19,155 :: ERROR :: 400 - server_error : Internal Server Error`

**Comment by LAScotland** [comment]
Apologies - https://github.com/Flodu31/HomeAssistant-PeugeotIntegration/issues/66 - seems to be a duplicate issue.
