### ISSUE TITLE
400 internal server error

### ISSUE THREAD

**Issue by kujrv1** [Flodu31/HomeAssistant-PeugeotIntegration#67]
Hi, I'm trying to deploy and i'm returning 400 internal server error for Peugeor e2008 car and ES country

2024-01-26 07:22:11,263 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-26 07:22:11,263 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-26 07:22:11,264 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-26 07:22:11,264 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-26 07:22:11,264 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-26 07:22:11,265 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-26 07:22:11,265 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-26 07:22:11,265 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-26 07:22:11,265 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-26 07:22:11,266 :: INFO :: Namespace mapping (56, 451) already seen! This is usually not a problem but could indicate packers or broken AXML compilers.
2024-01-26 07:22:11,278 :: WARNING :: Requested API level 33 is larger than maximum we have, returning API level 28 instead.
2024-01-26 07:22:12,560 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-26 07:22:12,561 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-26 07:22:12,562 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-26 07:22:12,563 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-26 07:22:12,564 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-26 07:22:12,565 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-26 07:22:12,566 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-26 07:22:12,566 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-26 07:22:12,566 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-26 07:22:12,567 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-26 07:22:12,567 :: WARNING :: RES_TABLE_LIBRARY_TYPE chunk is not supported
2024-01-26 07:22:14,955 :: ERROR :: 400  - server_error : Internal Server Error
Traceback (most recent call last):
  File "/home/parallels/.local/lib/python3.10/site-packages/psa_car_controller/web/view/config_views.py", line 133, in connectPSA
    res = firstLaunchConfig(app_name, email, password, countrycode)
  File "/home/parallels/.local/lib/python3.10/site-packages/psa_car_controller/psa/setup/app_decoder.py", line 95, in firstLaunchConfig
    psacc.connect(client_email, client_password)
  File "/home/parallels/.local/lib/python3.10/site-packages/psa_car_controller/psacc/application/psa_client.py", line 35, in connect
    self.manager.init_with_user_credentials_realm(user, password, self.realm)
  File "/home/parallels/.local/lib/python3.10/site-packages/psa_car_controller/psa/oauth.py", line 26, in init_with_user_credentials_realm
    self._token_request(self._grant_password_request_realm(login, password, realm), True)
  File "/home/parallels/.local/lib/python3.10/site-packages/oauth2_client/credentials_manager.py", line 205, in _token_request
    CredentialManager._handle_bad_response(response)
  File "/home/parallels/.local/lib/python3.10/site-packages/oauth2_client/credentials_manager.py", line 87, in _handle_bad_response
    raise OAuthError(HTTPStatus(response.status_code), error.get('error'), error.get('error_description'))
oauth2_client.credentials_manager.OAuthError: 400  - server_error : Internal Server Error
2024-01-26 07:22:14,958 :: INFO :: 192.168.1.35 - - [26/Jan/2024 07:22:14] "POST /_dash-update-component HTTP/1.1" 200 -

**Comment by FilipeOS** [comment]
Check https://github.com/flobz/psa_car_controller/issues/733

I just don't know if this git needs to be updated too?

**Comment by iendicott** [comment]
I'm getting the same message now.
