### ISSUE TITLE
preconditioning error 500

### ISSUE THREAD

**Issue by PaddyRu** [Flodu31/HomeAssistant-PeugeotIntegration#71]
Logs say "remote_refresh_token isn't defined"
I just installed the integration following the instructions to bypass the initial login issue and in fact the remote_refresh_token is left null after it.

**Comment by videojedi** [comment]
same here.

> 2024-03-06 09:33:34,023 :: INFO :: Preconditioning: topic: psa/RemoteServices/from/cid/OV-ACNT200007898612/ThermalPrecond: {'asap': 'activate', 'programs': {'program1': {'day': [0, 0, 0, 0, 0, 0, 0], 'hour': 34, 'minute': 7, 'on': 0}, 'program2': {'day': [0, 0, 0, 0, 0, 0, 0], 'hour': 34, 'minute': 7, 'on': 0}, 'program3': {'day': [0, 0, 0, 0, 0, 0, 0], 'hour': 34, 'minute': 7, 'on': 0}, 'program4': {'day': [0, 0, 0, 0, 0, 0, 0], 'hour': 34, 'minute': 7, 'on': 0}}}
2024-03-06 09:33:34,271 :: ERROR :: remote_refresh_token isn't defined
2024-03-06 09:33:34,271 :: ERROR :: Can't refresh remote token 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/RemoteClient.py", line 173, in _refresh_remote_token
    otp_code = self.get_otp_code()
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/common/utils.py", line 23, in wrapper
    raise RateLimitException
psa_car_controller.common.utils.RateLimitException
