### ISSUE TITLE
Unable to connect anymore

### ISSUE THREAD

**Issue by alexpelli** [Flodu31/HomeAssistant-PeugeotIntegration#85]
Since some days I cannot connect anymore.
When I try connection procedure I receive following message:

Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 100, in __fetch_user_info res_dict = res2.json()["success"] KeyError: 'success' {"code":"495", "message": "Invalid or expired client certificate"}

Could you please help me to solve it?
Thanks

**Comment by alexpelli** [comment]
Sorry I cannot exactly understand how to proceed.. I have downloaded the file but it is corrupted

**Comment by d1ockers** [comment]
I am having the same issue since a few days, too.

**Comment by SavanFlou** [comment]
Same for me, Given the last percentage of battery, I would say it could not receive information from the servor since last Week-end (24-25/08)

**Comment by guydl012** [comment]
Had the same issue. I've  followed the setup process (login, identification code, OTP) again and it is working.
(Well the integration is working, Peugeot/Stellantis servers just work "when they want" but that is another issue ;) ).

**Comment by ExtinctSKB** [comment]
I have the same issue, was this solved?

> Since some days I cannot connect anymore. When I try connection procedure I receive following message:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/setup/app_decoder.py", line 100, in __fetch_user_info res_dict = res2.json()["success"] KeyError: 'success' {"code":"495", "message": "Invalid or expired client certificate"}
> 
> Could you please help me to solve it? Thanks
